--QUESTION 2
--CREATE COPY OF DEPARTMENTS TABLE 
CREATE TABLE DEPARTMENTS_COPY AS 
SELECT * FROM SYSTEM.DEPARTMENTS;

CREATE OR REPLACE PROCEDURE UPDATE_DEPARTMENTS(
    dept_id DEPARTMENTS_COPY.DEPARTMENT_ID%type,
    man_id DEPARTMENTS_COPY.MANAGER_ID%type )
AS
BEGIN
  UPDATE DEPARTMENTS_COPY SET MANAGER_ID = man_id WHERE DEPARTMENT_ID =dept_id;
END;

--SAMPLE RUN
BEGIN
  UPDATE_DEPARTMENTS(10,121);
END;

--QUESTION 3
SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION GET_MANAGER_NAME(
    P_DEPT_ID NUMBER)
  RETURN VARCHAR
IS
V_EMP SYSTEM.EMPLOYEES%ROWTYPE;
BEGIN
  SELECT E.FIRST_NAME, E.LAST_NAME INTO V_EMP.FIRST_NAME, V_EMP.LAST_NAME
  FROM SYSTEM.DEPARTMENTS D JOIN SYSTEM.EMPLOYEES E
  ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
  WHERE D.DEPARTMENT_ID = P_DEPT_ID AND E.EMPLOYEE_ID = D.MANAGER_ID;
  
  RETURN (V_EMP.FIRST_NAME || ' ' || V_EMP.LAST_NAME || '');
END;

--SAMLE RUN 
EXECUTE DBMS_OUTPUT.PUT_LINE ('DEPARTMENT MANAGER: ' || GET_MANAGER_NAME(100));
